bind-tcp 127.0.0.1:53
cache-size 4096
cache-persist no
prefetch-domain yes
force-qtype-SOA 28 65
rr-ttl-min 300
speed-check-mode ping,tcp:443,tcp:80
response-mode first-ping
server-tls 1.1.1.1:853
server-tls 1.0.0.1:853
server-tls 8.8.8.8:853
max-reply-ip-num 3
log-level info